### ISSUE TITLE
[BUG提交]Uncaught ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by utrlman** [codercup/unibest#182]
# Bug report（问题描述）
```
06:38:59.532 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught ReferenceError: TextEncoder is not defined
 at  (app-service.js:18757:21)
 at  (app-service.js:33894:3)
```
H5 内置正常显示内容 ，到了真机和wx小程序就白屏只剩tabbar了。前几天翻找源码查到是pinia未初始化就引用了 当时解决了现在又点不然了。之前那次用uibest空项目写也还是有问题？是我生产环境有问题么？我查了下这个东西是web api 说是移动端没有  我下了安装步骤也没用 。疑问是否跟request文件里的东西有关？ 虽然我尝试换过ui http这些都无法解决 

## Screenshot or Gif（截图或动态图）
只有这行报错了  33894后面是代码map
![image](https://github.com/user-attachments/assets/b0f16da1-440e-482d-a6d4-a262a1f4de58)

## minimal reproduction（最小可还原代码）

 System:
    OS: Windows 11
  Binaries:
    Node: 20.18.0 - 
    npm: 10.9.0 - 
    pnpm: 9.12.2 - 
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vue: 3.4.21 => 3.4.21

贴一下pnpm：
```
 省略...
  "dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-components": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-h5": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-4010520240507001",
    "@iconify/vue": "^4.1.2",
    "alova": "^3.1.1",
    "crypto-js": "^4.2.0",
    "dayjs": "1.11.10",
    "pinia": "2.0.36",
    "pinia-plugin-persistedstate": "4.1.2",
    "qs": "6.5.3",
    "text-decoding": "^1.0.0",
    "uview-plus": "^3.3.37",
    "vue": "3.4.21",
    "vue-qr": "^4.0.9",
    "wot-design-uni": "^1.3.13",
    "z-paging": "^2.7.10"
  },
  "devDependencies": {
    "@commitlint/cli": "^18.6.1",
    "@commitlint/config-conventional": "^18.6.3",
    "@dcloudio/types": "^3.4.8",
    "@dcloudio/uni-automator": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-4010520240507001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-4010520240507001",
    "@esbuild/darwin-arm64": "0.20.2",
    "@esbuild/darwin-x64": "0.20.2",
    "@iconify-json/carbon": "^1.1.35",
    "@iconify/json": "^2.2.264",
    "@rollup/rollup-darwin-x64": "^4.18.0",
    "@types/node": "^20.14.2",
    "@types/wechat-miniprogram": "^3.4.7",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "@uni-helper/uni-types": "1.0.0-alpha.3",
    "@uni-helper/vite-plugin-uni-layouts": "^0.1.10",
    "@uni-helper/vite-plugin-uni-manifest": "^0.2.6",
    "@uni-helper/vite-plugin-uni-pages": "0.2.20",
    "@uni-helper/vite-plugin-uni-platform": "^0.0.4",
    "@unocss/preset-legacy-compat": "^0.59.4",
    "@vue/runtime-core": "^3.4.29",
    "@vue/tsconfig": "^0.1.3",
    "autoprefixer": "^10.4.19",
    "commitlint": "^18.6.1",
    "czg": "^1.9.3",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-standard": "^17.1.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-vue": "^9.26.0",
    "husky": "^8.0.3",
    "lint-staged": "^15.2.7",
    "postcss": "^8.4.38",
    "postcss-html": "^1.7.0",
    "postcss-scss": "^4.0.9",
    "rollup-plugin-visualizer": "^5.12.0",
    "sass": "^1.77.5",
    "stylelint": "^16.6.1",
    "stylelint-config-html": "^1.1.0",
    "stylelint-config-recess-order": "^4.6.0",
    "stylelint-config-recommended": "^14.0.0",
    "stylelint-config-recommended-scss": "^14.0.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-prettier": "^5.0.0",
    "terser": "^5.31.1",
    "typescript": "^5.5.4",
    "unocss": "^0.58.9",
    "unocss-applet": "^0.7.8",
    "unplugin-auto-import": "^0.17.6",
    "vite": "5.2.8",
    "vite-plugin-restart": "^0.4.0",
    "vue-tsc": "^1.8.27"
  }
}
```
vite没有动过
```
   build: {
      // 方便非h5端调试
      sourcemap: VITE_SHOW_SOURCEMAP === 'true', // 默认是false
      target: 'es6',
      // 开发环境不用压缩
      minify: mode === 'development' ? false : 'terser',
      terserOptions: {
        compress: {
          drop_console: VITE_DELETE_CONSOLE === 'true',
          drop_debugger: true,
        },
      },
    },
```

**Comment by utrlman** [comment]
貌似是vue-qr引起的问题 也可能是缓存的缘故  ...我自己的问题  文件覆盖了   打扰了
